### ISSUE TITLE
Error using `-i` option in ssh command after adding the public key to authorized_keys

### ISSUE THREAD

**Issue by Suprabat** [jamesog/yubikey-ssh#12]
In the following line, I believe only `-I` option is required, and `-i` actually results in error because the library is not an identity file
`ssh -I /usr/local/lib/opensc-pkcs11.so -i /usr/local/lib/opensc-pkcs11.so -o IdentitiesOnly=yes server.example.com`

p/s: Thanks for the guide, it really helps a lot, I'm very new to this.

**Comment by jamesog** [comment]
Thanks for the report. Can you confirm which platform you're on and which OpenSSH version? The commands listed are all copy/pasted from what I ran on macOS 10.15 which worked at the time.

I'm glad the guide helped!

**Comment by jamesog** [comment]
I'll close this out for now, let me know if this still causes an issue for you.
